const mongoose = require('mongoose');

// Define the schema
const labReportSchema = new mongoose.Schema({
    patientName: { type: String, required: true },
    email: { type: String },
    age: { type: Number, required: true },
    sex: { type: String, required: true },
    doctorName: { type: String, required: true },
    medicalName: { type: String, required: true },
    date: { type: Date, required: true },
    address: { type: String, required: true },
    interpretation: { type: String },
    hb: String,
    tlc: String,
    basophil: String,
    dlc: String,
    poly: String,
    lympho: String,
    mono: String,
    eosino: String,
    esr: String,
    pcv: String,
    bleedingTime: String,
    clottingTime: String,
    pt: String,
    inr: String,
    plateletCount: String,
    reticCount: String,
    rbcCount: String,
    mcv: String,
    mch: String,
    mchc: String,
    bloodgroup: String,
    crp: String,
    raFactor: String,
    hPylori: String,
    hiv: String,
    hbsAgTest: String,
    hcv: String,
    vdrl: String,
    dengue: String,
    scrub:String,
    mp: String,
    troponin: String,
    sTyphiO: String,
    sTyphiH: String,
    sParaTyphiAH: String,
    sParaTyphiBH: String,
    bloodSugarF: String,
    bloodSugarPP: String,
    bloodSugarR: String,
    fasting: String,
    firstHour: String,
    secondHour: String,
    thirdHour: String,
    bloodUrea: String,
    serumCreatinine: String,
    serumUricAcid: String,
    sCholesterol: String,
    sTriglycerides: String,
    vldlCholesterol: String,
    hdlCholesterol: String,
    ldlCholesterol: String,
    sBilirubinTotal: String,
    sBilirubinDirect: String,
    sProteinsTotal: String,
    sAlbumin: String,
    ggtp: String,
    sAlkalinePhos: String,
    sgpt: String,
    sgot: String,
    sSodium: String,
    sPotassium: String,
    sChloride: String,
    sPhosphorous: String,
    serumCalcium: String,
    hba1c: String,
    amylase: String,
    ckMb: String,
    colour: String,
    specificgravity: String,
    appearance: String,
    chemicalexamination: String,
    reaction: String,
    albumen: String,
    sugar: String,
    ketonebodies: String,
    blood: String,
    puscells: String,
    rbc: String,
    epcells: String,
    crystals: String,
    cast: String,
    others: String,
    pregnancytest: String,
    colourofstool: String,
    consistancyofstool: String,
    mucousofstool: String,
    chemicalexaminationofstool: String,
    reactionofstool: String,
    reducingsubstanceofstool: String,
    occultbloodofstool: String,
    protozoalparasitesofstool: String,
    bloodofstool: String,
    puscellsofstool: String,
    rbcofstool: String,
    helmenthicparasitesofstool: String,
    othersofstool: String,
    noteofstool: String,
    noteofwidaltest: String,

    labAssistant: { type: String }
});

// Create the model
const LabReport = mongoose.model('LabReport', labReportSchema);

module.exports = LabReport;
